import type { Metadata } from "next";
// import localFont from "next/font/local";
import { Michroma } from "next/font/google";
import "./globals.css";

const michroma = Michroma({
  weight: "400", // Specify the font weight you need
  subsets: ["latin"], // Character subset
});


export const metadata: Metadata = {
  title: "TechVilla",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={michroma.className} >
      <body
        className={` antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
